workflows:
  ios-workflow:
    name: iOS Beta Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: frontend_temp
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Pod install
        script: |
          cd ios
          pod install
      - name: Build iOS (unsigned)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - amrahulsaini@example.com
  
  android-workflow:
    name: Android Beta Build
    max_build_duration: 60
    instance_type: linux_x2
    working_directory: frontend_temp
    environment:
      flutter: stable
      android_signing:
        - jf_app_keystore
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - amrahulsaini@example.com
